# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
 - stage: Exploration
   pool:
     vmImage: ubuntu-latest
  
   jobs:
   - job: Mensaje_Bienvenida
     steps:
     - script: echo Hello, world!
       displayName: 'Run a one-line script'

     - script: |
         echo Add other tasks to build, test, and deploy your project.
         echo See https://aka.ms/yaml
       displayName: 'Run a multi-line script'
